### ISSUE TITLE
Job results do not include "Geo".

### ISSUE THREAD

**Issue by LiamJDesmond84** [falkenbach/actor-glassdoor-jobs#31]
jobLocation: 'Warren, MI',
url: 'https://www.glassdoor.com/job-listing/

Per this page: https://apify.com/alexey/glassdoor-jobs-scraper#scraped-glassdoor-jobs

The example included geolocation data, but there are none in the results.  Do I have to set this up differently to get them?

**Comment by zpelechova** [comment]
Hey, I ran it and got the jobLocation ok, can you post the url of your run maybe?

**Comment by LiamJDesmond84** [comment]
Hey, I can get the jobLocation just fine, just not the GeoLocation inside of it which is what I'm looking for.  I'm using the same code that was given here:

https://apify.com/alexey/glassdoor-jobs-scraper/api#glassdoor-jobs-salaries-companies-and-reviews-scraper

```
const input = {
    "startUrl": "",
    "maxResults": 4,
    "query": "Java Developer",
    "location": "Seattle",
    "locationstate": "WA",
    "proxy": {
        "useApifyProxy": true
    }
};


(async () => {
    // Run the actor and wait for it to finish
    const run = await client.actor("alexey/glassdoor-jobs-scraper").call(input);

    // Fetch and print actor results from the run's dataset (if any)
    console.log('Results from dataset');
    const { items } = await client.dataset(run.defaultDatasetId).listItems();
    items.forEach((item) => {
        console.dir(item);
    });
})();```
